### ISSUE TITLE
Expose decorations on descriptors

### ISSUE THREAD

**Issue by fintelia** [PENGUINLIONG/spirq-rs#49]
Currently it doesn't seem to be possible to expose what decorations are associated with a specific descriptor, but this would be very helpful information to expose. Right now I'm interested in knowing whether storage images are tagged as NonWritable or NonReadable, but there are surely other uses that people could be interested in.

**Comment by PENGUINLIONG** [comment]
Providing access to all decorations for types seems not very plausible, because it will largely change the structure of this crate. But I can change the definition of [`AccessType`](https://docs.rs/spirq/0.4.10/spirq/enum.AccessType.html) so that it represents how this variable is declared to be accessed. Then you can get what you want via [`get_desc_access`](https://docs.rs/spirq/0.4.10/spirq/struct.Manifest.html#method.get_desc_access).

**Comment by PENGUINLIONG** [comment]
Since the it's been addressed, I'm closing this issue. Feel free to reopen it for any follow-up.
